import type { Metadata } from 'next';
import NavBar from '@/components/NavBar/NavBar';
import Player from '@/components/Player/Player';
import SideMenu from '@/components/SideMenu/SideMenu';

export const metadata: Metadata = {
  title: 'Musician',
  description: 'Generated by create next app',
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen  max-h-screen flex-col flex-1 p-3 gap-3">
      <div className="flex flex-1 flex-rol gap-3 ">
        <SideMenu />
        <div className="flex flex-1 rounded-lg flex-col bg-black-800  gap-3 ">
          <div className="flex flex-col flex-grow gap-3 overflow-x-hidden overflow-y-auto h-0">
            <NavBar />
            <div className='p-4'>{children}</div>
          </div>
        </div>
      </div>
      <Player />
    </div>
  );
}
