import type { Metadata } from "next";
import MusicProvider from "@/context/MusicContext";
import NavBar from "@/components/NavBar/NavBar";
import Player from "@/components/Player/Player";
import SideMenu from "@/components/SideMenu/SideMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <MusicProvider>
      <div className="flex h-screen max-h-screen flex-col flex-1 p-3 gap-3">
        <div className="flex flex-1 flex-rol gap-3 ">
          <SideMenu />
          <div className="flex flex-1 flex-col rounded-lg bg-black-800 p-3 gap-3 ">
            <NavBar />
            <div className="flex flex-1 flex-col gap-3 overflow-hidden h-817 max-h-817">
              <div className="flex flex-col overflow-y-auto">{children}</div>
            </div>
          </div>
        </div>
        <Player />
      </div>
    </MusicProvider>
  );
}
