import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({children,}: {children: React.ReactNode}) {
  return (
    <div className="flex h-full flex-1 items-center justify-center">
      {children}
    </div>
  );
}
