import MusicProvider from "@/context/MusicContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContextProvider from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Musician",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen bg-black-950 text-white overflow-hidden ">
        <AuthContextProvider>
          <MusicProvider>{children}</MusicProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
